SECTION TEXT
MOD1:
	INPUT	N1		; INICIALIZA N1
	INPUT	N2		; INICIALIZA N2
	INPUT	N3		; INICIALIZA N3
	JMP		MOD2	; IMPRIME O MAIOR DEPOIS O MENOR
	
	RETURN:	STOP	; RETORNO AO MOD1 FINALIZA O PROGRAMA

MOD2:
	LOAD	N1							; ACC <- N1
	SUB		N2							; ACC = N1 - N2
	JMPP	N1_MAIOR_QUE_N2
	
	;N2_MAIOR_QUE_N1:
		LOAD	N2						; ACC <- N1
		SUB		N3						; ACC = N2 - N3
		JMPP	N2_MAIOR_QUE_N1_E_N3
		
			;CASO_N3_N1:
				OUTPUT	N3
				OUTPUT	N1
				JMP		RETURN
		
		N2_MAIOR_QUE_N1_E_N3:
			LOAD	N1					; ACC <- N1
			SUB		N3					; ACC = N1 - N3
			JMPP	CASO_N2_N3
			
			;CASO_N2_N1:
				OUTPUT	N2
				OUTPUT	N1
				JMP		RETURN
			
			CASO_N2_N3:
				OUTPUT	N2
				OUTPUT	N3
				JMP		RETURN
	
	N1_MAIOR_QUE_N2:
		LOAD	N1						; ACC <- N1
		SUB		N3						; ACC = N1 - N3
		JMPP	N1_MAIOR_QUE_N2_E_N3
	
			;CASO_N3_N2:
				OUTPUT	N3
				OUTPUT	N2
				JMP		RETURN
	
		N1_MAIOR_QUE_N2_E_N3:
			LOAD	N2					; ACC <- N2
			SUB		N3					; ACC = N2 - N3
			JMPP	CASO_N1_N3
			
			;CASO_N1_N2:
				OUTPUT	N1
				OUTPUT	N2
				JMP		RETURN
			
			CASO_N1_N3:
				OUTPUT	N1
				OUTPUT	N3
				JMP		RETURN
	
SECTION DATA
	N1:	SPACE
	N2:	SPACE
	N3:	SPACE

